### ISSUE TITLE
на открытом эвенте и плейсе оставить карту с одной точкой

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/nightcity2html#11]
http://joxi.ru/GrqMgkKfllakrz 
код вызывающий эту карту должен быть другой, гораздо проще

**Comment by AlexiySergeevich** [comment]
+

http://prntscr.com/cwrd5w

предлагаю поменять их местами, чтоб карта была слева

**Comment by noxonsu** [comment]
нет пуст справа будет
