### ISSUE TITLE
правки от дизайнера

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/nightcity2html#40]
[6:20:01] Unvab Design диз: 1) Разные отступы между колонками, не соблюдена сетка.
Здесь по 40: http://joxi.ru/DmB0gKnUpoWxAP
Здесь по 30: http://joxi.ru/52aZXW8TYyeqA0
Правильные отступы по 30.

2) Следующие отступы показываю как правильно и должно быть:
http://joxi.ru/eAONE8ltegDY2o

3) Вот этот момент я вообще не понял, все косо-криво:
http://joxi.ru/Dr8OazvC3bpZA6

4) Текст укоротить по ширине:
http://joxi.ru/LmG0gO8Ujkpg2l

5) Тоже текст укоротить по ширине:
http://joxi.ru/J2baxd9I1avvm6

6) Тут тоже укоротить, чтобы больше места было до края:
http://joxi.ru/krD0ga8U9n3Xrp

7) Тут отступы сделать по 100 px:
http://joxi.ru/xAeOyZJCvyZ8my

Это только главная. Остальные не смотрел, тк это слишком долго будет. Пусть делать по аналогии с главной и сравнивает с макетом.
[6:20:22] Unvab Design диз: Поправка к 7 пункту: по 60px, не 100

**Comment by AlexiySergeevich** [comment]
+
