### ISSUE TITLE
http://joxi.ru/KAxe9qXCGGNzr8 убрать абсолютные сссылки

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/nightcity2html#8]
http://joxi.ru/KAxe9qXCGGNzr8

**Comment by AlexiySergeevich** [comment]
вот здесь тоже ставим ссылку от каталога? или тут должна быть все-таки внешняя ссылка?

http://prntscr.com/cwrvbi

также прохожусь по всем js и html, css файлам

**Comment by noxonsu** [comment]
конечно должна быть локальная ссылка

**Comment by AlexiySergeevich** [comment]
+
